before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - checkstyle
  - docgen
  - publish

.build_template: &build_template_def
  stage: build
  artifacts:
    expire_in: 4 hours
    paths:
    - echoframework/build/outputs

build_debug:
  <<: *build_template_def
  only:
    - develop
  script:
    - ./gradlew :echoframework:assembleDebug

build_release:
  <<: *build_template_def
  only:
    - master
  script:
    - ./gradlew :echoframework:assembleRelease

unit_test:
  stage: test
  only:
    - master
    - develop
  script:
    - ./gradlew :echoframework:testReleaseUnitTest
  artifacts:
    expire_in: 4 hours
    paths:
      - echoframework/build/reports/tests

code_analysis:
  stage: checkstyle
  script:
    - ./gradlew :echoframework:lint :echoframework:analyzeCode
  artifacts:
    expire_in: 4 hours
    paths:
      - echoframework/build/reports/detekt

pages:
  stage: docgen
  only:
    - master
  script:
    - ./gradlew :echoframework:dokkaJavadoc
    - mkdir public
    - mv echoframework/build/javadoc/* public
  artifacts:
    paths:
      - public

maven_publishing:
  stage: publish
  only:
    - master
  script:
    - ./gradlew :echoframework:clean :echoframework:install :echoframework:bintrayUpload -PbintrayUser=$bintrayUserVar -PbintrayApiKey=$bintrayApiKeyVar
