before_script:
  - set ANDROID_HOME=D:\sdk

stages:
  - build
  - test
  - checkstyle
  - docgen

.build_template: &build_template_def
  stage: build
  artifacts:
    expire_in: 4 hours
    paths:
    - echoframework/build/outputs
    - echoframework/build/javadoc

build_debug:
  <<: *build_template_def
  only:
    - develop
    - feature/gitlab_configuration

  script:
    - gradlew assembleDebug

build_release:
  <<: *build_template_def
  only:
    - master
  script:
    - gradlew assembleRelease

unit_test:
  stage: test
  only:
    - master
    - develop
  script:
    - gradlew test
  artifacts:
    expire_in: 4 hours
    paths:
      - echoframework/build/reports/tests

code_analysis:
  stage: checkstyle
  script:
    - gradlew lint analyzeCode
  artifacts:
    expire_in: 4 hours
    paths:
      - echoframework/build/reports/detekt

doc_generation:
  stage: docgen
  only:
    - master
    - develop
  script:
    - gradlew dokka